# SMTP server configuration
spring.mail.host=smtp.office365.com
spring.mail.port=587
spring.mail.username=shamsher.yadav@nojatatechnology.com
spring.mail.password=dgjrgsjkgdxjtrwv
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Application mail settings
app.mail.from=shamsher.yadav@nojatatechnology.com
